hyperracing_dbt:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: C:/dev/duckdbdbt/hyperracing.duckdb
      threads: 1
weather_pipeline:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: /mnt/c/dev/canadian-weather-data-pipeline/data/warehouse/weather.duckdb
      threads: 4
      schema: main
