hyperracing_dbt:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: C:/dev/duckdbdbt/hyperracing.duckdb
      threads: 1
weather_pipeline:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: "{{ env_var('DBT_DUCKDB_PATH') }}"
      threads: 4
      schema: main